FROM cyberdojofoundation/clangplusplus:ee058a5
LABEL maintainer=jon@jaggersoft.com

COPY catch_main.cpp /usr/src
COPY install.sh .
RUN ./install.sh && rm ./install.sh
COPY red_amber_green.rb /usr/local/bin
