name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: cd docker/ && sudo cp catch_main.cpp /usr/src/ && sudo bash install.sh

      - name: Make check_bypass
        working-directory: check_bypass
        run: make
